# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vial < Formula
  desc "The centralized secret vault for vibe coders"
  homepage "https://one-vial.org"
  version "0.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.0.4/vial_0.0.4_darwin_amd64.tar.gz"
      sha256 "e309475f52a03fd8561ada9a1e56bdde0bb3b3524353acffef1e0af5a2859b72"

      define_method(:install) do
        bin.install "vial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.0.4/vial_0.0.4_darwin_arm64.tar.gz"
      sha256 "35207e78e0710261d26e05b4da12846f2253e2e3990b73e0e608803533a22aed"

      define_method(:install) do
        bin.install "vial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.0.4/vial_0.0.4_linux_amd64.tar.gz"
      sha256 "f8065b1e1d4cc8dde2f72bfc6cffcd66fd4b24d9999cab4776ed8be99ec1a66f"
      define_method(:install) do
        bin.install "vial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.0.4/vial_0.0.4_linux_arm64.tar.gz"
      sha256 "422e099c1fd4b9dcae97fab0455c3b1fb123c3c8c3af45ebf4d4ccffe9e5484b"
      define_method(:install) do
        bin.install "vial"
      end
    end
  end

  test do
    system "#{bin}/vial", "version"
  end
end
