# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vial < Formula
  desc "The centralized secret vault for vibe coders"
  homepage "https://one-vial.org"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.2.0/vial_0.2.0_darwin_amd64.tar.gz"
      sha256 "7c019070ef2fe420504f67e97dea26028fd0f9d1995ef19a5ce8118f9ede3702"

      define_method(:install) do
        bin.install "vial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.2.0/vial_0.2.0_darwin_arm64.tar.gz"
      sha256 "7f7285c644c2af5b1e784361d9b2e7f111ebb702941f73c140b39cd7f91bcd9f"

      define_method(:install) do
        bin.install "vial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.2.0/vial_0.2.0_linux_amd64.tar.gz"
      sha256 "112286c080f08e5a0526137d02dab710bfae1f7d163bed0c88e1718ba0eced0d"
      define_method(:install) do
        bin.install "vial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.2.0/vial_0.2.0_linux_arm64.tar.gz"
      sha256 "362f18683d759039ee8d9a0a319977f7d213dde25e36a63a8929e188af91f2b6"
      define_method(:install) do
        bin.install "vial"
      end
    end
  end

  def post_install
    # Remove quarantine attribute so unsigned binary runs on macOS
    system_command "xattr", args: ["-d", "com.apple.quarantine", bin/"vial"], print_stderr: false
  end

  test do
    system "#{bin}/vial", "version"
  end
end
