# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vial < Formula
  desc "The centralized secret vault for vibe coders"
  homepage "https://one-vial.org"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.1.1/vial_0.1.1_darwin_amd64.tar.gz"
      sha256 "9c9c6d1f612cdd68d77a37ecdea72e67294fa7e4124243f2bea9a836e4c97142"

      define_method(:install) do
        bin.install "vial"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.1.1/vial_0.1.1_darwin_arm64.tar.gz"
      sha256 "8f6279d69a6f660e3258cf31f3d25cae222e757e32ef9bf896022e4ef2f69ce2"

      define_method(:install) do
        bin.install "vial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.1.1/vial_0.1.1_linux_amd64.tar.gz"
      sha256 "8b1f6e7e9ef504186069acfb38e884ee065ab7b1632d6456ec5a3ff6900285a9"
      define_method(:install) do
        bin.install "vial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cheesejaguar/vial/releases/download/v0.1.1/vial_0.1.1_linux_arm64.tar.gz"
      sha256 "81d44843949704e77c166bbd6a1421ba744811aa76aac64fb955f1330aca7099"
      define_method(:install) do
        bin.install "vial"
      end
    end
  end

  def post_install
    # Remove quarantine attribute so unsigned binary runs on macOS
    system_command "xattr", args: ["-d", "com.apple.quarantine", bin/"vial"], print_stderr: false
  end

  test do
    system "#{bin}/vial", "version"
  end
end
